# Generated by Django 4.2.7 on 2026-09-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='session_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
