# Generated by Django 4.2.7 on 2026-09-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_session_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='patient_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='rolling_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='summarized_up_to_turn',
            field=models.IntegerField(default=0),
        ),
    ]
